sudo: required
services:
  - docker
before_install:
  - docker pull php:7.3.9-alpine3.10
  - echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

script:
  - docker build -t cjy632258/php-base .

after_success:
  - docker push cjy632258/php-base