name: Build

on:
  push:
    tags: [ release/* ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: Build the Docker image
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}
        IMAGE=cjy632258/php-base
        docker build --tag $IMAGE:latest --tag $IMAGE:$IMAGE_TAG .
        docker push $IMAGE:latest 
        docker push $IMAGE:$IMAGE_TAG